function byId<T extends HTMLElement>(id: string): T {
    return document.getElementById(id) as T;
}

export let searchForm: HTMLFormElement;
export let searchInput: HTMLInputElement;
export let searchSuggestions: HTMLUListElement;
export let shortcutsGrid: HTMLDivElement;
export let addShortcutBtn: HTMLButtonElement;
export let modalOverlay: HTMLDivElement;
export let shortcutName: HTMLInputElement;
export let shortcutUrl: HTMLInputElement;
export let cancelBtn: HTMLButtonElement;
export let saveBtn: HTMLButtonElement;
export let modalTitle: HTMLHeadingElement;
export let confirmOverlay: HTMLDivElement;
export let confirmText: HTMLParagraphElement;
export let confirmCancelBtn: HTMLButtonElement;
export let confirmDeleteBtn: HTMLButtonElement;
export let confirmTitle: HTMLHeadingElement;
export let presetList: HTMLDivElement;
export let savePresetBtn: HTMLButtonElement;
export let presetOverlay: HTMLDivElement;
export let presetModalTitle: HTMLHeadingElement;
export let presetName: HTMLInputElement;
export let presetCancelBtn: HTMLButtonElement;
export let presetSaveBtn: HTMLButtonElement;
export let exportOverlay: HTMLDivElement;
export let exportPresetsCheck: HTMLInputElement;
export let exportCancelBtn: HTMLButtonElement;
export let exportConfirmBtn: HTMLButtonElement;
export let importOverlay: HTMLDivElement;
export let importSummary: HTMLParagraphElement;
export let importModeApply: HTMLInputElement;
export let importModePreset: HTMLInputElement;
export let importAsPresetRow: HTMLLabelElement;
export let importNameGroup: HTMLDivElement;
export let importPresetName: HTMLInputElement;
export let importCancelBtn: HTMLButtonElement;
export let importConfirmBtn: HTMLButtonElement;
export let historyImportInput: HTMLInputElement;
export let widgetLayer: HTMLDivElement;
export let widgetList: HTMLDivElement;
export let addWidgetBtn: HTMLButtonElement;
export let arrangeBtn: HTMLButtonElement;
export let arrangeDoneBtn: HTMLButtonElement;
export let gridCols: HTMLInputElement;
export let gridRows: HTMLInputElement;
export let gridColsValue: HTMLSpanElement;
export let gridRowsValue: HTMLSpanElement;
export let widgetOverlay: HTMLDivElement;
export let widgetModalTitle: HTMLHeadingElement;
export let widgetType: HTMLSelectElement;
export let widgetCode: HTMLTextAreaElement;
export let widgetHosts: HTMLInputElement;
export let widgetHostsHint: HTMLDivElement;
export let widgetGrantRow: HTMLDivElement;
export let widgetGrantBtn: HTMLButtonElement;
export let widgetGrantHint: HTMLDivElement;
export let widgetSource: HTMLInputElement;
export let widgetFetchBtn: HTMLButtonElement;
export let widgetFileBtn: HTMLButtonElement;
export let widgetFileInput: HTMLInputElement;
export let widgetConfigGroup: HTMLDivElement;
export let widgetConfigFields: HTMLDivElement;
export let widgetW: HTMLInputElement;
export let widgetH: HTMLInputElement;
export let widgetX: HTMLInputElement;
export let widgetY: HTMLInputElement;
export let widgetCard: HTMLInputElement;
export let widgetError: HTMLParagraphElement;
export let widgetCancelBtn: HTMLButtonElement;
export let widgetSaveBtn: HTMLButtonElement;
export let settingsZone: HTMLDivElement;
export let settingsBtn: HTMLButtonElement;
export let settingsClose: HTMLButtonElement;
export let logoEl: HTMLHeadingElement;
export let subtitleEl: HTMLParagraphElement;
export let shortcutsTitleEl: HTMLElement;
export let footerEl: HTMLElement;
export let introTip: HTMLDivElement;
export let fontSelect: HTMLSelectElement;
export let engineSelect: HTMLSelectElement;
export let customFontRow: HTMLDivElement;
export let titleFontSelect: HTMLSelectElement;
export let customTitleFontRow: HTMLDivElement;
export let titleColorRow: HTMLDivElement;
export let titleAngleRow: HTMLDivElement;
export let customEngineRow: HTMLDivElement;
export let presetsEl: HTMLDivElement;
export let imageInput: HTMLInputElement;
export let imageHint: HTMLDivElement;
export let themeStatus: HTMLDivElement;
export let bgUrlInput: HTMLInputElement;
export let importInput: HTMLInputElement;
export let commandList: HTMLDivElement;
export let addCommandBtn: HTMLButtonElement;
export let commandOverlay: HTMLDivElement;
export let commandModalTitle: HTMLHeadingElement;
export let commandName: HTMLInputElement;
export let commandType: HTMLSelectElement;
export let commandUrls: HTMLTextAreaElement;
export let commandTemplate: HTMLInputElement;
export let commandUrlsGroup: HTMLDivElement;
export let commandTemplateGroup: HTMLDivElement;
export let commandHint: HTMLInputElement;
export let commandCodeGroup: HTMLDivElement;
export let commandCode: HTMLTextAreaElement;
export let commandHosts: HTMLInputElement;
export let commandGrants: HTMLDivElement;
export let supportNotice: HTMLDivElement;
export let supportNoticeClose: HTMLButtonElement;
export let exportScriptWarning: HTMLParagraphElement;
export let importScriptWarning: HTMLParagraphElement;
export let commandCancelBtn: HTMLButtonElement;
export let commandSaveBtn: HTMLButtonElement;
export let contextMenu: HTMLDivElement;
export let contextMenuTitle: HTMLDivElement;
export let contextEditBtn: HTMLButtonElement;
export let contextDeleteBtn: HTMLButtonElement;
export let toast: HTMLDivElement;
export let bgFull: HTMLDivElement;
export let cssEditor: HTMLTextAreaElement;
export let clearCssBtn: HTMLButtonElement;
export let safeModeNote: HTMLDivElement;
export let extensionGroup: HTMLDivElement;

export let titleColor2Row: HTMLDivElement;

export function initDom() {
    titleColor2Row = byId<HTMLDivElement>('titleColor2Row');
    searchForm = byId<HTMLFormElement>('searchForm');
    searchInput = byId<HTMLInputElement>('searchInput');
    searchSuggestions = byId<HTMLUListElement>('searchSuggestions');
    shortcutsGrid = byId<HTMLDivElement>('shortcutsGrid');
    addShortcutBtn = byId<HTMLButtonElement>('addShortcutBtn');
    modalOverlay = byId<HTMLDivElement>('modalOverlay');
    shortcutName = byId<HTMLInputElement>('shortcutName');
    shortcutUrl = byId<HTMLInputElement>('shortcutUrl');
    cancelBtn = byId<HTMLButtonElement>('cancelBtn');
    saveBtn = byId<HTMLButtonElement>('saveBtn');
    modalTitle = byId<HTMLHeadingElement>('modalTitle');
    confirmOverlay = byId<HTMLDivElement>('confirmOverlay');
    confirmText = byId<HTMLParagraphElement>('confirmText');
    confirmCancelBtn = byId<HTMLButtonElement>('confirmCancelBtn');
    confirmDeleteBtn = byId<HTMLButtonElement>('confirmDeleteBtn');
    confirmTitle = byId<HTMLHeadingElement>('confirmTitle');
    presetList = byId<HTMLDivElement>('presetList');
    savePresetBtn = byId<HTMLButtonElement>('savePresetBtn');
    presetOverlay = byId<HTMLDivElement>('presetOverlay');
    presetModalTitle = byId<HTMLHeadingElement>('presetModalTitle');
    presetName = byId<HTMLInputElement>('presetName');
    presetCancelBtn = byId<HTMLButtonElement>('presetCancelBtn');
    presetSaveBtn = byId<HTMLButtonElement>('presetSaveBtn');
    exportOverlay = byId<HTMLDivElement>('exportOverlay');
    exportPresetsCheck = byId<HTMLInputElement>('exportPresetsCheck');
    exportCancelBtn = byId<HTMLButtonElement>('exportCancelBtn');
    exportConfirmBtn = byId<HTMLButtonElement>('exportConfirmBtn');
    importOverlay = byId<HTMLDivElement>('importOverlay');
    importSummary = byId<HTMLParagraphElement>('importSummary');
    importModeApply = byId<HTMLInputElement>('importModeApply');
    importModePreset = byId<HTMLInputElement>('importModePreset');
    importAsPresetRow = byId<HTMLLabelElement>('importAsPresetRow');
    importNameGroup = byId<HTMLDivElement>('importNameGroup');
    importPresetName = byId<HTMLInputElement>('importPresetName');
    importCancelBtn = byId<HTMLButtonElement>('importCancelBtn');
    importConfirmBtn = byId<HTMLButtonElement>('importConfirmBtn');
    historyImportInput = byId<HTMLInputElement>('historyImportInput');
    widgetLayer = byId<HTMLDivElement>('widgetLayer');
    widgetList = byId<HTMLDivElement>('widgetList');
    addWidgetBtn = byId<HTMLButtonElement>('addWidgetBtn');
    arrangeBtn = byId<HTMLButtonElement>('arrangeBtn');
    arrangeDoneBtn = byId<HTMLButtonElement>('arrangeDoneBtn');
    gridCols = byId<HTMLInputElement>('gridCols');
    gridRows = byId<HTMLInputElement>('gridRows');
    gridColsValue = byId<HTMLSpanElement>('gridColsValue');
    gridRowsValue = byId<HTMLSpanElement>('gridRowsValue');
    widgetOverlay = byId<HTMLDivElement>('widgetOverlay');
    widgetModalTitle = byId<HTMLHeadingElement>('widgetModalTitle');
    widgetType = byId<HTMLSelectElement>('widgetType');
    widgetCode = byId<HTMLTextAreaElement>('widgetCode');
    widgetHosts = byId<HTMLInputElement>('widgetHosts');
    widgetHostsHint = byId<HTMLDivElement>('widgetHostsHint');
    widgetGrantRow = byId<HTMLDivElement>('widgetGrantRow');
    widgetGrantBtn = byId<HTMLButtonElement>('widgetGrantBtn');
    widgetGrantHint = byId<HTMLDivElement>('widgetGrantHint');
    widgetSource = byId<HTMLInputElement>('widgetSource');
    widgetFetchBtn = byId<HTMLButtonElement>('widgetFetchBtn');
    widgetFileBtn = byId<HTMLButtonElement>('widgetFileBtn');
    widgetFileInput = byId<HTMLInputElement>('widgetFileInput');
    widgetConfigGroup = byId<HTMLDivElement>('widgetConfigGroup');
    widgetConfigFields = byId<HTMLDivElement>('widgetConfigFields');
    widgetW = byId<HTMLInputElement>('widgetW');
    widgetH = byId<HTMLInputElement>('widgetH');
    widgetX = byId<HTMLInputElement>('widgetX');
    widgetY = byId<HTMLInputElement>('widgetY');
    widgetCard = byId<HTMLInputElement>('widgetCard');
    widgetError = byId<HTMLParagraphElement>('widgetError');
    widgetCancelBtn = byId<HTMLButtonElement>('widgetCancelBtn');
    widgetSaveBtn = byId<HTMLButtonElement>('widgetSaveBtn');
    settingsZone = byId<HTMLDivElement>('settingsZone');
    settingsBtn = byId<HTMLButtonElement>('settingsBtn');
    settingsClose = byId<HTMLButtonElement>('settingsClose');
    logoEl = byId<HTMLHeadingElement>('logo');
    subtitleEl = byId<HTMLParagraphElement>('subtitle');
    shortcutsTitleEl = byId<HTMLElement>('shortcutsTitle');
    footerEl = document.querySelector('.footer') as HTMLElement;
    introTip = byId<HTMLDivElement>('introTip');
    fontSelect = byId<HTMLSelectElement>('fontSelect');
    engineSelect = byId<HTMLSelectElement>('engineSelect');
    customFontRow = byId<HTMLDivElement>('customFontRow');
    titleFontSelect = byId<HTMLSelectElement>('titleFontSelect');
    customTitleFontRow = byId<HTMLDivElement>('customTitleFontRow');
    titleColorRow = byId<HTMLDivElement>('titleColorRow');
    titleAngleRow = byId<HTMLDivElement>('titleAngleRow');
    customEngineRow = byId<HTMLDivElement>('customEngineRow');
    presetsEl = byId<HTMLDivElement>('presets');
    imageInput = byId<HTMLInputElement>('imageInput');
    imageHint = byId<HTMLDivElement>('imageHint');
    themeStatus = byId<HTMLDivElement>('themeStatus');
    bgUrlInput = byId<HTMLInputElement>('bgUrl');
    importInput = byId<HTMLInputElement>('importInput');
    commandList = byId<HTMLDivElement>('commandList');
    addCommandBtn = byId<HTMLButtonElement>('addCommandBtn');
    commandOverlay = byId<HTMLDivElement>('commandOverlay');
    commandModalTitle = byId<HTMLHeadingElement>('commandModalTitle');
    commandName = byId<HTMLInputElement>('commandName');
    commandType = byId<HTMLSelectElement>('commandType');
    commandHint = byId<HTMLInputElement>('commandHint');
    commandCodeGroup = byId<HTMLDivElement>('commandCodeGroup');
    commandCode = byId<HTMLTextAreaElement>('commandCode');
    commandHosts = byId<HTMLInputElement>('commandHosts');
    commandGrants = byId<HTMLDivElement>('commandGrants');
    supportNotice = byId<HTMLDivElement>('supportNotice');
    supportNoticeClose = byId<HTMLButtonElement>('supportNoticeClose');
    exportScriptWarning = byId<HTMLParagraphElement>('exportScriptWarning');
    importScriptWarning = byId<HTMLParagraphElement>('importScriptWarning');
    commandUrls = byId<HTMLTextAreaElement>('commandUrls');
    commandTemplate = byId<HTMLInputElement>('commandTemplate');
    commandUrlsGroup = byId<HTMLDivElement>('commandUrlsGroup');
    commandTemplateGroup = byId<HTMLDivElement>('commandTemplateGroup');
    commandCancelBtn = byId<HTMLButtonElement>('commandCancelBtn');
    commandSaveBtn = byId<HTMLButtonElement>('commandSaveBtn');
    contextMenu = byId<HTMLDivElement>('contextMenu');
    contextMenuTitle = byId<HTMLDivElement>('contextMenuTitle');
    contextEditBtn = byId<HTMLButtonElement>('contextEditBtn');
    contextDeleteBtn = byId<HTMLButtonElement>('contextDeleteBtn');
    toast = byId<HTMLDivElement>('toast');
    bgFull = byId<HTMLDivElement>('bgFull');
    cssEditor = byId<HTMLTextAreaElement>('cssEditor');
    clearCssBtn = byId<HTMLButtonElement>('clearCssBtn');
    safeModeNote = byId<HTMLDivElement>('safeModeNote');
    extensionGroup = byId<HTMLDivElement>('extensionGroup');
}
